version: '3'

services:

  # Next.js frontend ---------------------------------------------
  app:
    profiles: ["cpu", "cuda", "xla", "ggml", "metal"]
    build:
      context: ./next
      dockerfile: Dockerfile
    image: llm-on-prem-app
    working_dir: /app
    command: "node server.js"
    env_file:
      - ./next/.env.local
    network_mode: host
    # ports:
    #   - 3000:3000

  # Model Controller ---------------------------------------------
  fastchat-controller:
    profiles: ["cpu", "cuda", "xla", "ggml", "metal"]
    build:
      context: ./models
      dockerfile: cpu.Dockerfile
    image: fastchat:latest
    ports:
      - "21001:21001"
    entrypoint: ["python3", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]

  # API Server ---------------------------------------------
  fastchat-api-server:
    profiles: ["cpu", "cuda", "xla", "ggml", "metal"]
    build:
      context: ./models
      dockerfile: cpu.Dockerfile
    image: fastchat:latest
    ports:
      - "8000:8000"
    entrypoint: ["python3", 
                 "-m", "fastchat.serve.openai_api_server",
                 "--controller-address", "http://fastchat-controller:21001",
                 "--host", "0.0.0.0",
                 "--port", "8000"]

  # Model Worker Cuda ---------------------------------------------
  fastchat-model-worker-cuda:
    profiles: ["cuda"]
    build:
      context: ./models
      dockerfile: cuda.Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
    image: fastchat:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3",
                  "-m", "fastchat.serve.vllm_worker",
                  "--model-names", "${FASTCHAT_WORKER_MODEL_NAMES:-mpt-7b-chat}",
                  "--model-path", "mosaicml/mpt-7b-chat",
                  "--worker-address", "http://fastchat-model-worker:21002",
                  "--controller-address", "http://fastchat-controller:21001",
                  "--device", "cuda",
                  "--host", "0.0.0.0",
                  "--port", "21002"]
  
  # Model Worker CPU ---------------------------------------------
  fastchat-model-worker-cpu:
    profiles: ["cpu"]
    build:
      context: ./models
      dockerfile: cpu.Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
    image: fastchat:latest
    entrypoint: ["python3",
                  "-m", "fastchat.serve.model_worker",
                  "--model-names", "${FASTCHAT_WORKER_MODEL_NAMES:-mpt-7b-chat}",
                  "--model-path", "mosaicml/mpt-7b-chat",
                  "--worker-address", "http://fastchat-model-worker:21002",
                  "--controller-address", "http://fastchat-controller:21001",
                  "--device", "cpu",
                  "--host", "0.0.0.0",
                  "--port", "21002"]
  
volumes:
  huggingface: