version: '3'

services:

  # Next.js frontend ---------------------------------------------
  app:
    profiles: ["cpu", "cuda", "xla", "ggml", "metal", "openvino"]
    build:
      context: ./next
      dockerfile: Dockerfile
    image: llm-on-prem-app
    working_dir: /app
    command: "node server.js"
    env_file:
      - .env
    network_mode: host
    # ports:
    #   - 3000:3000

  # API Server ---------------------------------------------
  fastchat-api-server:
    profiles: ["cpu", "cuda", "xla", "ggml", "metal", "openvino"]
    build:
      context: ./models
      dockerfile: cpu.Dockerfile
    image: fastchat-cpu:latest
    network_mode: host
    # ports:
      # - "8000:8000"
    entrypoint: ["python3", 
                 "-m", "fastchat.serve.openai_api_server",
                #  "--controller-address", "http://fastchat-controller:21001",
                 "--controller-address", "http://localhost:21001",
                 "--host", "0.0.0.0",
                 "--port", "8000"]

  # Model Controller ---------------------------------------------
  fastchat-controller:
    profiles: ["cpu", "cuda", "xla", "ggml", "metal", "openvino"]
    build:
      context: ./models
      dockerfile: cpu.Dockerfile
    image: fastchat-cpu:latest
    network_mode: host
    # ports:
      # - "21001:21001"
    entrypoint: ["python3", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]

  # Model Worker Cuda ---------------------------------------------
  fastchat-model-worker-cuda:
    profiles: ["cuda"]
    build:
      context: ./models
      dockerfile: cuda.Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
    image: fastchat-cuda:latest
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3",
                  "-m", "fastchat.serve.vllm_worker",
                  "--model-names", "${FASTCHAT_WORKER_MODEL_NAMES:-Llama-2-7b-chat-hf}",
                  "--model-path", "meta-llama/Llama-2-7b-chat-hf",
                  "--worker-address", "http://fastchat-model-worker-cuda:21002",
                  "--controller-address", "http://fastchat-controller:21001",
                  "--device", "cuda",
                  "--host", "0.0.0.0",
                  "--port", "21002"]
  
  # Model Worker CPU ---------------------------------------------
  fastchat-model-worker-cpu:
    profiles: ["cpu"]
    build:
      context: ./models
      dockerfile: cpu.Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
    image: fastchat-cpu:latest
    env_file:
      - .env
    entrypoint: ["python3",
                  "-m", "fastchat.serve.model_worker",
                  "--model-names", "${FASTCHAT_WORKER_MODEL_NAMES:-Llama-2-7b-chat-hf}",
                  "--model-path", "meta-llama/Llama-2-7b-chat-hf",
                  "--worker-address", "http://fastchat-model-worker-cpu:21002",
                  "--controller-address", "http://fastchat-controller:21001",
                  "--device", "cpu",
                  "--host", "0.0.0.0",
                  "--port", "21002"]

  fastchat-model-worker-openvino:
    profiles: ["openvino"]
    env_file:
      - .env
    build:
      context: ./models
      dockerfile: openvino.Dockerfile
    volumes:
      - /home/chepe/.cache/huggingface:/home/openvino/.cache/huggingface
      - /home/chepe/rad-ninjas/code/FastChat:/home/openvino/FastChat
      - /home/chepe/rad-ninjas/code/openvino/models:/home/openvino/models
    image: fastchat-openvino:latest
    working_dir: /home/openvino/FastChat
    entrypoint: ["python3",
                 "fastchat/serve/openvino_worker.py",
                 "--model-names", "${FASTCHAT_WORKER_MODEL_NAMES:-llama-2-7b-chat-hf}",
                 "--model-path", "/home/openvino/models/llama-2/ir_model",
                 "--worker-address", "http://fastchat-model-worker-openvino:21002",
                 "--controller-address", "http://fastchat-controller:21001",
                 "--host", "0.0.0.0",
                 "--port", "21002"]
    ports:
      - 21002:21002


  
volumes:
  huggingface:
